version: '3.8'  # ใช้เวอร์ชันล่าสุดเพื่อความเข้ากันได้
services:
  n8n:
    image: n8nio/n8n:latest  # ระบุ tag :latest เพื่อใช้เวอร์ชันล่าสุด
    restart: unless-stopped  # รีสตาร์ทอัตโนมัติเมื่อไม่หยุดเอง
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_PASSWORD}
      - N8N_HOST=${RAILWAY_STATIC_URL}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - TZ=Asia/Bangkok
    volumes:
      - n8n_data:/home/node/.n8n
    # เพิ่ม healthcheck เพื่อตรวจสอบสถานะ container
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5678/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  n8n_data:
